// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LevelDBService provides LevelDB database operations for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseDatabase closes the currently open database.
 */
export function CloseDatabase(): $CancellablePromise<void> {
    return $Call.ByID(2257836302);
}

/**
 * DeleteKey deletes the given key.
 * keyDisplay uses the same format as returned by GetKeys.
 */
export function DeleteKey(keyDisplay: string): $CancellablePromise<void> {
    return $Call.ByID(277474761, keyDisplay);
}

/**
 * GetKeys returns all keys in the currently open database.
 * Keys are returned in lexicographic order.
 * Non-UTF-8 keys are hex-encoded.
 */
export function GetKeys(): $CancellablePromise<string[]> {
    return $Call.ByID(3118125663).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetValue returns the value for the given key.
 * The key should be in the same format as returned by GetKeys (UTF-8 or hex with "0x" prefix).
 * Non-UTF-8 values are hex-encoded in the response.
 */
export function GetValue(keyDisplay: string): $CancellablePromise<string> {
    return $Call.ByID(2570607492, keyDisplay);
}

/**
 * OpenDatabase opens a LevelDB database at the given path.
 * Returns Ok=true on success, Ok=false with Error set when the path is not a valid LevelDB database.
 */
export function OpenDatabase(path: string): $CancellablePromise<$models.OpenDatabaseResult> {
    return $Call.ByID(1785735212, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PutValue creates or updates the value for a key.
 * Key and value use the same display format as GetKeys/GetValue (UTF-8 or "0x" prefixed hex).
 */
export function PutValue(keyDisplay: string, valueDisplay: string): $CancellablePromise<void> {
    return $Call.ByID(2473207079, keyDisplay, valueDisplay);
}

/**
 * PutValueIfUnchanged updates a key only if its current value matches expectedValueDisplay.
 * Set force=true to overwrite regardless of current database value.
 */
export function PutValueIfUnchanged(keyDisplay: string, expectedValueDisplay: string, newValueDisplay: string, force: boolean): $CancellablePromise<$models.PutValueIfUnchangedResult> {
    return $Call.ByID(1648540501, keyDisplay, expectedValueDisplay, newValueDisplay, force).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RenameKey renames a key while preserving its value.
 * oldKeyDisplay and newKeyDisplay use the same key format as GetKeys.
 */
export function RenameKey(oldKeyDisplay: string, newKeyDisplay: string): $CancellablePromise<void> {
    return $Call.ByID(2279504418, oldKeyDisplay, newKeyDisplay);
}

/**
 * SetDatabaseLocked sets whether write operations are blocked for the open database.
 */
export function SetDatabaseLocked(locked: boolean): $CancellablePromise<void> {
    return $Call.ByID(659892384, locked);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.OpenDatabaseResult.createFrom;
const $$createType2 = $models.PutValueIfUnchangedResult.createFrom;
