// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * OpenDatabaseResult is the result of opening a LevelDB database.
 */
export class OpenDatabaseResult {
    "ok": boolean;
    "error": string;
    "canonicalPath": string;
    "alreadyOpen": boolean;
    "readOnly": boolean;
    "forcedReadOnly": boolean;
    "intentionalReadOnly": boolean;
    "readOnlyReason": string;
    "lockedByApp": string;

    /** Creates a new OpenDatabaseResult instance. */
    constructor($$source: Partial<OpenDatabaseResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("canonicalPath" in $$source)) {
            this["canonicalPath"] = "";
        }
        if (!("alreadyOpen" in $$source)) {
            this["alreadyOpen"] = false;
        }
        if (!("readOnly" in $$source)) {
            this["readOnly"] = false;
        }
        if (!("forcedReadOnly" in $$source)) {
            this["forcedReadOnly"] = false;
        }
        if (!("intentionalReadOnly" in $$source)) {
            this["intentionalReadOnly"] = false;
        }
        if (!("readOnlyReason" in $$source)) {
            this["readOnlyReason"] = "";
        }
        if (!("lockedByApp" in $$source)) {
            this["lockedByApp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenDatabaseResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenDatabaseResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenDatabaseResult($$parsedSource as Partial<OpenDatabaseResult>);
    }
}

/**
 * PutValueIfUnchangedResult is the result of a guarded value write.
 */
export class PutValueIfUnchangedResult {
    "ok": boolean;
    "conflict": boolean;
    "currentValue": string;
    "currentValueExists": boolean;

    /** Creates a new PutValueIfUnchangedResult instance. */
    constructor($$source: Partial<PutValueIfUnchangedResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("conflict" in $$source)) {
            this["conflict"] = false;
        }
        if (!("currentValue" in $$source)) {
            this["currentValue"] = "";
        }
        if (!("currentValueExists" in $$source)) {
            this["currentValueExists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PutValueIfUnchangedResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PutValueIfUnchangedResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PutValueIfUnchangedResult($$parsedSource as Partial<PutValueIfUnchangedResult>);
    }
}
