// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService provides desktop window-level actions for the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
} from "@wailsio/runtime";

/**
 * ToggleCurrentWindowMenuBar toggles the active window menu bar on Windows.
 */
export function ToggleCurrentWindowMenuBar(): $CancellablePromise<void> {
  return $Call.ByID(2520651002);
}
