// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * OpenDatabaseResult is the result of opening a LevelDB database.
 */
export class OpenDatabaseResult {
    "ok": boolean;
    "error": string;

    /** Creates a new OpenDatabaseResult instance. */
    constructor($$source: Partial<OpenDatabaseResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenDatabaseResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenDatabaseResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenDatabaseResult($$parsedSource as Partial<OpenDatabaseResult>);
    }
}
